### ISSUE TITLE
ignoreSslErrors toggle appears to be nonfunctional

### ISSUE THREAD

**Issue by ariacomputer** [Appdynamics/url-monitoring-extension#2]
This references Request #68310.

It does not appear that the value set by the ignoreSslErrors toggle in the client config is actually being used by the code, at least as far as configuring the client.

I've added code similar to the followRedirects toggle in a submitted pull request, but have not been able to test the code.

I've gone back through the repo's history and as far as I can tell, this issue has been occurring since at least the point where the software was refactored, i.e., at least version 1.0.5, the oldest version available in the repo.

Here is a snippet of the error generated when using ignoreSslErrors on an SSL site with a self-signed certificate:

> [New I/O worker #11] 22 Jul 2016 16:38:11,911 ERROR ThreadedUrlMonitor - https://redacteddomain.com:443/index.htm -> FAILED: General SSLEngine problem
> java.net.ConnectException: General SSLEngine problem
>         at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
>         at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37)
>         at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:104)
>         at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
>         at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395)
>         at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
>         at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1460)
>         at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1314)
>         at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
>         at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
>         at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
>         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
>         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
>         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
>         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
>         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
>         at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
>         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
>         at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
>         at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
>         at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>         at sun.security.ssl.Handshaker.checkThrown(Unknown Source)
>         at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source)
>         at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source)
>         at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source)
>         at javax.net.ssl.SSLEngine.unwrap(Unknown Source)
>         at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
>         ... 18 more
> Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
>         at sun.security.ssl.Alerts.getSSLException(Unknown Source)
>         at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
>         at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
>         at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
>         at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
>         at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
>         at sun.security.ssl.Handshaker.processLoop(Unknown Source)
>         at sun.security.ssl.Handshaker$1.run(Unknown Source)
>         at sun.security.ssl.Handshaker$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source)
>         at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
>         at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
>         ... 18 more
> **Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address REDACTEDIP found**
>         at sun.security.util.HostnameChecker.matchIP(Unknown Source)
>         at sun.security.util.HostnameChecker.match(Unknown Source)
>         at sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
>         at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
>         at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
>         ... 27 more

**Comment by ariacomputer** [comment]
Issue appears to be resolved in the newest version.
